name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
    inputs:
      # Hardhat configuration
      hardhat-version:
        type: string
        description: 'Hardhat version'
        required: false
        default: "1.1.0"
      zksync-contracts-version:
        type: string
        description: 'ZKsync contracts version'
        required: false
        default: "0.6.1"
      zksync-ethers-version:
        type: string
        description: 'ZKsync ethers version'
        required: false
        default: "6.11.0"
      # Compilers configuration
      zksolc-version:
        type: string
        description: 'Zksolc version'
        required: false
        default: "latest"
      solidity-version:
        type: string
        description: 'Solidity version'
        required: false
        default: "0.8.27"


jobs:

  # This job is supposed to check hardhat template
  # with the most recent version of Hardhat
  # and with the most recent version of compilers
  hardhat:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    strategy:
      matrix:
        include:
          - name: Solidity
            directory: 'templates/hardhat/solidity'
          - name: Vyper
            directory: 'templates/hardhat/vyper'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: matter-labs/zksync-contract-templates

      - name: Patch hardhat dependencies
        run: |
          yarn add @matterlabs/hardhat-zksync@${{ inputs.hardhat-version || '1.2.0' }}
          yarn add @matterlabs/zksync-contracts@${{ inputs.zksync-contracts-version || '0.6.1' }}
          yarn add zksync-ethers@${{ inputs.zksync-ethers-version || '6.11.0' }}

      - name: Update compilers config
        run: |
          sed -i 's/version: "latest"/version: process.env.ZKSOLC_VERSION || "latest"/' hardhat.config.ts
          sed -i 's/version: "0.8.17"/version: process.env.SOLIDITY_VERSION || "0.8.17"/' hardhat.config.ts
          cat hardhat.config.ts

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        env:
          ZKSOLC_VERSION: ${{ inputs.zksolc-version || '1.5.4' }}
          SOLIDITY_VERSION: ${{ inputs.solidity-version || '0.8.27' }}
        run: yarn test
