name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    strategy:
      matrix:
        include:
          - name: Solidity
            directory: 'templates/hardhat/solidity'
          - name: Vyper
            directory: 'templates/hardhat/vyper'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: matter-labs/zksync-contract-templates

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies for ${{ matrix.name }}
        run: yarn install --frozen-lockfile

      - name: Run ${{ matrix.name }} tests
        run: yarn test
