name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  # This job is supposed to check hardhat template
  # with the most recent version of Hardhat
  # and with the most recent version of compilers


  # Compiler versions in hardhat.config.js
  # zksolc: {
  #   version: "latest",
  #   settings: {
  #     // find all available options in the official documentation
  #     // https://docs.zksync.io/build/tooling/hardhat/hardhat-zksync-solc#configuration
  #   },
  # },
  # solidity: {
  #   version: "0.8.17",
  # },

  # "@matterlabs/hardhat-zksync": "^1.1.0",
  # "@matterlabs/zksync-contracts": "^0.6.1",
  # "zksync-ethers": "^6.11.0"

  hardhat:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    strategy:
      matrix:
        include:
          - name: Solidity
            directory: 'templates/hardhat/solidity'
          - name: Vyper
            directory: 'templates/hardhat/vyper'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: matter-labs/zksync-contract-templates

      - name: Update hardhat config
        run: |
          sed -i 's/version: "latest"/version: process.env.ZKSOLC_VERSION || "latest"/' hardhat.config.ts
          sed -i 's/version: "0.8.17"/version: process.env.SOLIDITY_VERSION || "0.8.17"/' hardhat.config.ts
          cat hardhat.config.ts

      - name: Install dependencies for ${{ matrix.name }}
        run: yarn install

      - name: Run ${{ matrix.name }} tests
        env:
          ZKSOLC_VERSION: 1.5.4
          SOLIDITY_VERSION: 0.8.27
        run: yarn test
